Resources:
  AppEcsRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: sfn-runtask-retry-app
  AppTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: 256
      ExecutionRoleArn:
        Fn::GetAtt: AppTaskExecutionRole.Arn
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [ "FARGATE" ]
      ContainerDefinitions:
        - Name: app
          Essential: true
          Image:
            Fn::Join:
              - .
              - - Ref: AWS::AccountId
                - dkr.ecr
                - Ref: AWS::Region
                - Fn::Join:
                  - /
                  - - amazonaws.com
                    - { Ref: AppEcsRepository }
  AppTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
